language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"

# command to install dependencies
install:
  - pip install coverage coveralls .
# command to run tests
script: "coverage run -m unittest discover -s 'tests/' -p 'test_*.py'"
after_success: "coveralls"
